baseurl = "https://ml-stat.github.io/MLSTAT2023/"
languageCode = "en-us"
title = "MLSTAT 2023"
theme = "hugo-material-banner"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

[params]
	# General information
	# author = "Bruce Eckel"
	description = "A Self-Organizing Open-Spaces Unconference"

	logo = "/images/hsdA.png"
	favicon = "images/logo-color-small-2.png"
	banner_image = "/images/hsdC.jpg"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

  [params.palette]
  	primary = "indigo"
  	accent  = "red"

  [params.font]
  	text = "sans-serif"
  	code = "sans-serif Mono"


[social]
	twitter = ""
	github  = "/orgs/ML-Stat/repositories"
	email   = "xiangyuchang@stu.edu.cn"

[[menu.main]]
	name   = "Overview"
	url    = "overview"
	weight = 10

[[menu.main]]
	name   = "Committee"
	url    = "committee"
	weight = 40

[[menu.main]]
	name   = "Schedule"
	url    = "schedule"
	weight = 160

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true